[package]
edition = "2021"
name = "yew-app"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.6"
wasm-bindgen = "0.2"
wasm-logger = "0.2.0"
yew = "0.19"

[lib]
crate-type = ["rlib", "cdylib"]
